Repository CaddyDz/Isaac, pull requests merged in 2020-06, with the labels that each got.

#13 Explanations
  resources/views/explanations.blade.php
  resources/views/explanations/explanation.blade.php
  resources/views/explanations/index.blade.php
  routes/web.php
Labels: UI

#12 explanation files
  resources/views/explanations.blade.php
  resources/views/explanations/explanation.blade.php
  resources/views/explanations/index.blade.php
  routes/web.php
Labels: UI

#15 pluralize explanation title closes #14
  composer.json
  composer.lock
  resources/views/explanations/explanation.blade.php
  tests/Feature/ExplanaionsTest.php
Labels: localization

#19 PHP Only Style CI analyses closes #18
  .styleci.yml
Labels: enhancement, style

#17 closes #16
  resources/views/explanations/explanation.blade.php
  resources/views/lectures/lecture.blade.php
  resources/views/partials/related_articles.blade.php
Labels: UI

#20 Apply fixes from StyleCI
  app/Console/Kernel.php
  app/Exceptions/Handler.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/PagesController.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/CheckForMaintenanceMode.php
  app/Http/Middleware/EncryptCookies.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Middleware/TrustHosts.php
  app/Http/Middleware/TrustProxies.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Providers/BroadcastServiceProvider.php
  app/Providers/EventServiceProvider.php
  app/Providers/RouteServiceProvider.php
  app/Slide.php
  app/User.php
  bootstrap/app.php
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cache.php
  config/cors.php
  config/database.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/mail.php
  config/queue.php
  config/services.php
  config/session.php
  config/view.php
  database/factories/SlideFactory.php
  database/factories/UserFactory.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  database/migrations/2020_06_01_111845_create_slides_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/SlidesTableSeeder.php
  resources/lang/en/auth.php
  resources/lang/en/pagination.php
  resources/lang/en/passwords.php
  resources/lang/en/validation.php
  routes/api.php
  routes/channels.php
  routes/console.php
  routes/web.php
  tests/CreatesApplication.php
  tests/Feature/ExplanaionsTest.php
  tests/Feature/RoutesTest.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
Labels: style
